# Comparing and sorting

In [1]:
import numpy as np

### Attempting comparison in numpy array

In [36]:
rand_1 = np.random.randint(20, size=(2,3,3))

In [37]:
rand_1

array([[[10, 16, 15],
        [19, 10, 19],
        [13,  0,  2]],

       [[ 6,  7, 17],
        [15,  8,  1],
        [15,  8, 11]]])

In [38]:
rand_1[rand_1 > 5]

array([10, 16, 15, 19, 10, 19, 13,  6,  7, 17, 15,  8, 15,  8, 11])

In [39]:
rand_1 > 5

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True, False, False]],

       [[ True,  True,  True],
        [ True,  True, False],
        [ True,  True,  True]]])

In [48]:
rand_1[:, :2, :2].shape

(2, 2, 2)

# Sorting An Array

In [49]:
rand_1

array([[[10, 16, 15],
        [19, 10, 19],
        [13,  0,  2]],

       [[ 6,  7, 17],
        [15,  8,  1],
        [15,  8, 11]]])

In [51]:
np.sort(rand_1)

array([[[10, 15, 16],
        [10, 19, 19],
        [ 0,  2, 13]],

       [[ 6,  7, 17],
        [ 1,  8, 15],
        [ 8, 11, 15]]])

In [52]:
np.argsort(rand_1)

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [53]:
np.argmin(rand_1)

6

In [54]:
np.argmax(rand_1)

4