# Exercise Nut Butter Sales


In [54]:
#creating the the dataframe
import numpy as np
import pandas as pd

In [55]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [56]:
weekly_sale = pd.DataFrame(sales_amount,
                           index=["Mon", "Tue", "Wed","Thur", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])

In [57]:
weekly_sale

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [58]:
price = np.array([10, 8, 12])
price

array([10,  8, 12])

In [59]:
price

array([10,  8, 12])

In [60]:
butter_prices= pd.DataFrame(price.reshape(1,3),
                           index=["price"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])

In [61]:
butter_prices

Almond butter  Peanut butter  Cashew butter
price             10              8             12

In [62]:
weekly_sale

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [63]:
butter_prices

Almond butter  Peanut butter  Cashew butter
price             10              8             12

### creating the total column in butter nut

### In doing the dot matrix calculation 
    *The shape of the the array really matter
    * It may be neccessary to transpose

In [64]:
weekly_sale["Total($)"] = np.dot(weekly_sale, butter_prices.T)

In [65]:
weekly_sale

Almond butter  Peanut butter  Cashew butter  Total($)
Mon              12             15              0       240
Tue               3              3              7       138
Wed               9             19             18       458
Thur              4              6             12       232
Fri               1              6              7       142