# Introduction To Numpy

In [28]:
import numpy as np

## Datatype and Attributes

In [29]:
# creating an array 
a1 = np.array([4,5,3,4,5,3])
a1

array([4, 5, 3, 4, 5, 3])

In [30]:
type(a1)

numpy.ndarray

In [31]:
a2 = np.array([[2,4,3], [6,4,6]])
a3 = np.array([[[2,3,3],[6,5,4],[4,3,5]], [[4,34,5],[5,6,3],[5,3,2]]])
a2

array([[2, 4, 3],
       [6, 4, 6]])

In [32]:
a3

array([[[ 2,  3,  3],
        [ 6,  5,  4],
        [ 4,  3,  5]],

       [[ 4, 34,  5],
        [ 5,  6,  3],
        [ 5,  3,  2]]])

In [33]:
a3.shape

(2, 3, 3)

In [34]:
a1.shape

(6,)

In [35]:
a2.shape

(2, 3)

In [36]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [37]:
a1.dtype, a2.dtype

(dtype('int64'), dtype('int64'))

In [38]:
a1.size, a3.size

(6, 18)

In [39]:
type(a1)

numpy.ndarray

## creating array

In [40]:
ones = np.ones((4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
zeros = np.zeros((4,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
range_num = np.arange(3, 30, 0.5)
range_num

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,
        8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5,
       14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. ,
       19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5,
       25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

In [43]:
randon_array = np.random.randint(3, 20, size=(3,5))
randon_array

array([[18, 13,  7, 10, 16],
       [ 4,  9,  7,  9,  4],
       [ 9, 10,  3, 10,  7]])

In [27]:
np.random.random((5,3))

array([[0.93289433, 0.04213141, 0.90423683],
       [0.52074482, 0.27924851, 0.5469832 ],
       [0.14122018, 0.41583107, 0.52091913],
       [0.19776822, 0.13256526, 0.94248053],
       [0.28707638, 0.5105994 , 0.5451607 ]])

In [53]:
# Using random seed
np.random.seed(seed=4)
random_4 = np.random.randint(0, 10, size=(3,5))
random_4

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2]])