# Manipulaton and Aggregation

### Aggregation

In [2]:
import numpy as np
a1 = np.array([1,2,4])
a1

array([1, 2, 4])

In [3]:
np.sum(a1)

7

In [9]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.75235303, 0.59672858, 0.20884486, 0.27502649, 0.45259371,
       0.99491973, 0.91541402, 0.99751239, 0.21075344, 0.84425589])

In [10]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

11.1 ms ± 72.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
53 µs ± 97.2 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
a2 = np.array([[3,2,4], [4,5,3]])
np.mean(a2), np.var(a2), np.std(a2)

(3.5, 0.9166666666666666, 0.9574271077563381)

## reshaping and transposing

In [14]:
a2 = np.array([[2,3,2], [4,3,4]])
a2

array([[2, 3, 2],
       [4, 3, 4]])

In [17]:
a2.reshape(2,3,1)

array([[[2],
        [3],
        [2]],

       [[4],
        [3],
        [4]]])

In [18]:
a2

array([[2, 3, 2],
       [4, 3, 4]])

In [19]:
a2.T

array([[2, 4],
       [3, 3],
       [2, 4]])

In [20]:
a2.transpose()

array([[2, 4],
       [3, 3],
       [2, 4]])