# Viewing array and Matrices in array

# finding a unique number


In [23]:
import numpy as np

In [24]:
#implementing random seed
np.random.seed(0)
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [25]:
# finding a unique number
nUnique = np.unique(random_array)
nUnique

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Selecting and Viewing Array

In [26]:
nUnique[0]

0

In [27]:
random_array[0]

array([5, 0, 3, 3, 7])

In [28]:
random_array[:2, :2]

array([[5, 0],
       [9, 3]])

In [31]:
# creating a larger array
a5 = np.random.randint(10, size=(2,3,4,5))
a5

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [40]:
a5[:2,:2, :3, :4]

array([[[[8, 8, 2, 3],
         [0, 8, 8, 3],
         [2, 8, 4, 3]],

        [[0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9]]],


       [[[6, 5, 8, 2],
         [9, 7, 5, 3],
         [5, 3, 3, 7]],

        [[3, 9, 7, 7],
         [1, 2, 2, 8],
         [5, 8, 4, 0]]]])

# Manipulating and Comparing array

## Arithmetic

In [42]:
a1 = np.array([1,2,3])
one = np.ones(3)

In [43]:
a1

array([1, 2, 3])

In [44]:
one

array([1., 1., 1.])

In [45]:
a1+one

array([2., 3., 4.])

In [46]:
a1-one

array([0., 1., 2.])

In [47]:
a1*one

array([1., 2., 3.])

In [49]:
a2 = np.array([[2,4,3], [4,6,5]])
a2

array([[2, 4, 3],
       [4, 6, 5]])

In [50]:
a1* a2

array([[ 2,  8,  9],
       [ 4, 12, 15]])

In [56]:
npray = np.random.randint(10, size=(3,5))
npray

array([[8, 8, 7, 0, 3],
       [8, 7, 7, 1, 8],
       [4, 7, 0, 4, 9]])

In [58]:
npray.transpose()

array([[8, 8, 4],
       [8, 7, 7],
       [7, 7, 0],
       [0, 1, 4],
       [3, 8, 9]])

In [59]:
a1*npray.transpose()

array([[ 8, 16, 12],
       [ 8, 14, 21],
       [ 7, 14,  0],
       [ 0,  2, 12],
       [ 3, 16, 27]])

In [63]:
np_dom =  npray.transpose()//a1
np_dom

array([[8, 4, 1],
       [8, 3, 2],
       [7, 3, 0],
       [0, 0, 1],
       [3, 4, 3]])

In [65]:
np_dom.shape

(5, 3)

## Concenpt of slicing

In [66]:
np_dom[:, :2]

array([[8, 4],
       [8, 3],
       [7, 3],
       [0, 0],
       [3, 4]])

In [69]:
np_dom[:3, :2]

array([[8, 4],
       [8, 3],
       [7, 3]])